import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  MatButtonModule, MatToolbarModule, MatCheckboxModule, MatMenuModule, MatIconModule,
  MatCardModule, MatInputModule, MatSidenavModule, MatDividerModule, MatListModule, MatFormFieldModule,
  MatSelectModule, MatTabsModule, MatGridListModule, MatButtonToggleModule, MatSlideToggleModule,
  MatRadioModule, MatTableModule, MatPaginatorModule, MatProgressSpinnerModule, MatButtonToggleGroup,
  MatSnackBarModule, MatSlideToggle, MatButtonToggle, MatButton, MatRadioGroup, MatSpinner, MatDialogModule,
  MatTooltipModule, MatPaginator, MatGridTile, MatGridList, MatTab, MatRadioButton
} from '@angular/material';

@NgModule({
  declarations: [],
  imports: [
    MatButtonModule,
    MatToolbarModule,
    MatCheckboxModule,
    MatMenuModule,
    MatIconModule,
    MatCardModule,
    MatInputModule,
    MatSidenavModule,
    MatDividerModule,
    MatListModule,
    MatFormFieldModule,
    MatSelectModule,
    MatTabsModule,
    MatGridListModule,
    MatButtonToggleModule,
    MatSlideToggleModule,
    MatRadioModule,
    MatGridListModule,
    MatTableModule,
    MatPaginatorModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
    MatDialogModule,
    MatTooltipModule
  ],
  exports: [
    MatButtonModule,
    MatToolbarModule,
    MatCheckboxModule,
    MatMenuModule,
    MatIconModule,
    MatCardModule,
    MatInputModule,
    MatSidenavModule,
    MatDividerModule,
    MatListModule,
    MatFormFieldModule,
    MatSelectModule,
    MatTabsModule,
    MatGridListModule,
    MatTableModule,
    MatSnackBarModule,
    MatDialogModule,
    MatTooltipModule,
    MatButtonToggleGroup,
    MatButtonToggle,
    MatSlideToggle,
    MatButton,
    MatRadioGroup,
    MatRadioButton,
    MatTab,
    MatGridList,
    MatGridTile,
    MatPaginator,
    MatSpinner,
  ]
})
export class AngularMaterialsModule { }
