INSERT INTO HOST (FIRSTNAME, LASTNAME, USERNAME, EMAIL, PASSWORD, WEBSITE, BIO, BIRTHDATE, CREATEDATE) VALUES ('Alex', ' Wolfe', 'uname', 'awolfe@gmail.com', 'pword', 'aaa.com', NULL, NULL, NULL);
-- INSERT INTO ADDRESS (ADDRESSID, STREETADDRESS, APARTMENT, CITY, STATE, ZIP) VALUES (1, '1234 CHERRY LANE', NULL,'DALLAS', 'TX', 75024);
-- INSERT INTO EVENT (EVENTID, EVENT_NAME, USERID, TIMESTART, TIMEEND, ADDRESSID, CAPTION, FLAG) VALUES (1, 'ROLLERBLADING', 1, TO_DATE ('2019-05-01 12:30:15','yyyy-mm-dd hh24:mi:ss'), TO_DATE ('2019-05-02 12:30:15','yyyy-mm-dd hh24:mi:ss'), 1, 'Best Event In Town', 0);
-- INSERT INTO USER_EVENT (userId, eventId) VALUE (1,1);
-- INSERT INTO USER_EVENT (USEREVENTID, USERID, EVENTID) VALUE (1,1,1);

