DROP TABLE IF EXISTS HOST;

CREATE TABLE HOST (
    HOSTID INT PRIMARY KEY,
    FIRSTNAME VARCHAR(250) NOT NULL,
    LASTNAME VARCHAR(250) NOT NULL,
    USERNAME VARCHAR(250) NOT NULL,
    EMAIL VARCHAR(250) NOT NULL,
    PASSWORD VARCHAR(250) NOT NULL,
    WEBSITE VARCHAR(250),
    BIO VARCHAR(250),
    BIRTHDATE VARCHAR(250),
    CREATEDATE DATETIME
)
